// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>

namespace Reporting.WebFormsDemo
{
    public partial class RegionSummary
    {
        protected global::System.Web.UI.HtmlControls.HtmlIframe pdfFrame;
    }
}
