// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>

namespace Reporting.WebFormsDemo
{
    public partial class SalesReport
    {
        protected global::System.Web.UI.WebControls.TextBox txtDateFrom;
        protected global::System.Web.UI.WebControls.TextBox txtDateTo;
        protected global::System.Web.UI.WebControls.DropDownList ddlRegion;
        protected global::System.Web.UI.WebControls.TextBox txtPreparedBy;
        protected global::System.Web.UI.WebControls.Button btnView;
        protected global::System.Web.UI.WebControls.Panel pnlPdf;
        protected global::System.Web.UI.HtmlControls.HtmlIframe pdfFrame;
    }
}
